version: '3.7'

services:
  postgres:
    ports:
      - ${POSTGRES_PORT}:5432

  testnet:
    image: "libraventures/monero-testnet:0.14.1"
    ports:
      - "127.0.0.1:180082:18082"
      - "127.0.0.1:28081:28081"
      - "127.0.0.1:38081:38081"
    volumes:
      - './chains:/monero/blockchain'
      - './wallets:/monero/wallets'
      - './logs:/monero/logs'
    hostname: monero-payer-testnet
    restart: unless-stopped