version: "3.7"

services:
  postgres:
    image: postgres:11-alpine
    container_name: monero-payer-postgres
    hostname: monero-payer-postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  ntwrk:
    external: true
